// FIGR Design System - Token export command
import { getLastTokens } from '../utils/tokensStore';
import { buildTokens } from './generate';
import { DesignTokens, GenerationConfig } from '../../shared/types';

export type ExportFormat = 'json' | 'css' | 'tailwind' | 'dtcg';

/**
 * Serialize the design system's tokens.
 *
 * tokensStore holds tokens in a module-level variable that dies with the plugin
 * sandbox, so on a fresh open there is nothing cached and export used to throw
 * "No design system has been generated yet" even when the user's config was
 * right there in the panel. Tokens are derived deterministically from config, so
 * fall back to rebuilding them instead of failing.
 */
export function exportTokens(format: ExportFormat, config?: GenerationConfig): string {
  const last = getLastTokens();
  const tokens = last ? last.tokens : config ? buildTokens(config) : null;
  if (!tokens) {
    throw new Error('No tokens to export. Configure a design system in the panel first.');
  }
  switch (format) {
    case 'css':
      return toCss(tokens);
    case 'tailwind':
      return toTailwind(tokens);
    case 'dtcg':
      return toDtcg(tokens);
    case 'json':
    default:
      return JSON.stringify(toJson(tokens), null, 2);
  }
}

function toJson(tokens: DesignTokens) {
  return {
    colors: tokens.colors,
    typography: tokens.typography,
    spacing: tokens.spacing,
    shadows: tokens.shadows,
    borderRadius: tokens.borderRadius,
  };
}

function colorVars(tokens: DesignTokens): string[] {
  const lines: string[] = [];
  for (const [name, ct] of Object.entries(tokens.colors)) {
    for (const [shade, hex] of Object.entries(ct.shades)) {
      lines.push(`  --color-${name}-${shade}: ${hex};`);
    }
  }
  return lines;
}

function toCss(tokens: DesignTokens): string {
  const lines: string[] = [':root {'];
  lines.push('  /* Color */');
  lines.push(...colorVars(tokens));
  lines.push('  /* Typography */');
  // font families aren't in tokens; use generic fallbacks
  lines.push('  --font-heading: Inter, sans-serif;');
  lines.push('  --font-body: Inter, sans-serif;');
  lines.push('  --font-mono: "IBM Plex Mono", monospace;');
  lines.push('  /* Spacing */');
  for (const s of tokens.spacing) lines.push(`  --space-${s.name}: ${s.value}px;`);
  lines.push('  /* Radius */');
  for (const r of tokens.borderRadius) lines.push(`  --radius-${r.name}: ${r.value};`);
  lines.push('  /* Elevation */');
  for (const s of tokens.shadows) lines.push(`  --shadow-${s.name}: ${s.value};`);
  lines.push('}');
  return lines.join('\n');
}

function toTailwind(tokens: DesignTokens): string {
  const colors: Record<string, Record<string, string>> = {};
  for (const [name, ct] of Object.entries(tokens.colors)) {
    colors[name] = {};
    for (const [shade, hex] of Object.entries(ct.shades)) colors[name][shade] = hex;
  }
  const spacing: Record<string, string> = {};
  for (const s of tokens.spacing) spacing[s.name] = `${s.value}px`;
  const radius: Record<string, string> = {};
  for (const r of tokens.borderRadius) radius[r.name] = r.value;
  const shadow: Record<string, string> = {};
  for (const s of tokens.shadows) shadow[s.name] = s.value;

  const obj = {
    theme: {
      extend: {
        colors,
        spacing,
        borderRadius: radius,
        boxShadow: shadow,
      },
    },
  };
  return `/** Tailwind CSS theme.extend — generated by FIGR Design System */\nmodule.exports = ${JSON.stringify(obj, null, 2)};`;
}

function toDtcg(tokens: DesignTokens): string {
  const dtcg: any = { color: {}, dimension: {}, borderRadius: {}, shadow: {} };
  for (const [name, ct] of Object.entries(tokens.colors)) {
    dtcg.color[name] = {};
    for (const [shade, hex] of Object.entries(ct.shades)) {
      dtcg.color[name][shade] = { $type: 'color', $value: hex };
    }
  }
  for (const s of tokens.spacing) {
    dtcg.dimension[`spacing-${s.name}`] = { $type: 'dimension', $value: `${s.value}px` };
  }
  for (const r of tokens.borderRadius) {
    dtcg.borderRadius[r.name] = { $type: 'borderRadius', $value: r.value };
  }
  for (const s of tokens.shadows) {
    dtcg.shadow[s.name] = { $type: 'shadow', $value: s.value };
  }
  return JSON.stringify(dtcg, null, 2);
}
